{% set name = "napari-nd-annotator" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1f1116cb88aa43c4a643ae9d706e43e7f13ce7405c7679492b6d6c18063ad2fe

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler("cxx") }}
    - {{ stdlib("c") }}
  host:
    - pip
    - python
    - cython
    - numpy
  run:
    - magicgui
    - matplotlib-base
    - napari >=0.4.11
    - numpy
    - opencv
    - python
    - qtpy
    - scikit-image >=0.19
    - simpleitk
    - vispy

test:
  imports:
    - napari_nd_annotator
    - napari_nd_annotator.mean_contour._essentials
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://github.com/bauerdavid/napari-nD-annotator
  summary: A toolbox for annotating objects one by one in nD
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bauerdavid
    - goanpeca
    - jaimergp
