{% set name = "napari-nd-annotator" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-nD-annotator-{{ version }}.tar.gz
  sha256: 8f8f6c41588a4f2ab091cac1b0cbaced21c297a83e2d50329a842fb252e27b39

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - magicgui
    - matplotlib-base
    - napari ==0.4.15
    - numpy
    - opencv
    - python >=3.8
    - qtpy
    - vispy

test:
  imports:
    - napari_nd_annotator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bauerdavid/napari-nD-annotator
  summary: A toolbox for annotating objects one by one in nD
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bauerdavid
    - goanpeca
    - jaimergp
