{% set name = "napari-nd-annotator" %}
{% set version = "0.0.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-nD-annotator-{{ version }}.tar.gz
  sha256: fa9122947149e44745b03fe498244e169007984d75e9fb6f713bb8b78050a5e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - {{ compiler('cxx') }} 
    - cython
    - numpy
    - pip
    - python >=3.8
    - scipy
    - setuptools
    - wheel
  run:
    - magicgui
    - matplotlib-base
    - napari ==0.4.15
    - numpy
    - opencv
    - python >=3.8
    - qtpy
    - scikit-image
    - vispy

test:
  imports:
    - napari_nd_annotator
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://github.com/bauerdavid/napari-nD-annotator
  summary: A toolbox for annotating objects one by one in nD
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - bauerdavid
    - goanpeca
    - jaimergp
